### ISSUE TITLE
error: docker build failed with exit code 2

### ISSUE THREAD

**Issue by jorgemrisco** [boardfish/waxseal#4]
![image](https://user-images.githubusercontent.com/61189874/103431228-c2863c00-4bab-11eb-90bb-d80cecc0cbff.png)

Greetings, I was  trying to implement your github action but I keep getting this error, I wonder if it's related to some docker configuration.
I've been using this repo https://github.com/jorgemrisco/markdown-to-latex-test

**Comment by boardfish** [comment]
Hey there! Thank you for checking out Waxseal.

From the build instructions, it looks like `tlmgr` needs to be updated within the container:

```
   Step 2/12 : RUN tlmgr update --all
   ---> Running in 15a7a9a2dd85
  ===============================================================================
  tlmgr itself needs to be updated.
  Please do this via either
    tlmgr update --self
  or by getting the latest updater for Unix-ish systems:
    http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh
  and/or Windows systems:
    http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.exe
  Then continue with other updates as usual.
  ===============================================================================
  tlmgr: An error has occurred. See above messages. Exiting.
  tlmgr: package repository http://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet (verified)
  The command '/bin/sh -c tlmgr update --all' returned a non-zero code: 2
```

I'll make an update to the `Dockerfile` and release this against the `v1.0.2` tag as soon as I can.

**Comment by boardfish** [comment]
Alright, I've pushed the tag. Please do let me know if it works for you!

**Comment by jorgemrisco** [comment]
Thanks for the quick reply! You're the man.
I'll make sure to test it later today or tomorrow and give you my feedback!

**Comment by jorgemrisco** [comment]
Yup, it worked perfectly!
